# SPDX-License-Identifier: SPDX-GPL-3.0-or-later
# GPL 3.0 or later
#
# 21 Nov 2023 tahomasoft
# bacon@tahomasoft.com Erik Beck

# This Makefile is for Rockchip RK3568 boards

include $(TOPDIR)/rules.mk

define Package/uboot-rockchip-3568
	SECTION:=boot
	CATEGORY:=Boot Loaders
	TITLE:=Package to build U-Boot for Rockchip-RK3568
	MAINTAINER:= Erik Beck bacon@tahomasoft.com
	LICENSE:=GPL-3.0 GPL-3.0+
endef

define Package/uboot-rockchip-3568/description
   Uboot for rk3568
endef


# uboot version 2023.10

# Package name below commented out because download routine uses it
# As directory name to use for downloading the source from the internet
# despite use of PKG_DISTNAME below

PKG_NAME:=uboot-rockchip-3568

# ATF_BL31:=rk3568_bl31_v1.43.elf
# ATF_BL32:=rk3568_bl32_v2.10.bin
# DDR:=rk3568_ddr_1560MHz_v1.18.bin
PKG_DISTNAME:=u-boot
PKG_VERSION:=2023.10
PKG_RELEASE:=0

PKG_BUILD_DEPENDS:=arm-trusted-firmware-rockchip-rkbin fstools

PKG_SOURCE:=$(PKG_DISTNAME)-$(PKG_VERSION).tar.bz2
PKG_SOURCE_URL:= \
	https://ftp.denx.de/pub/u-boot \
	https://mirror.cyberbits.eu/u-boot \
	ftp://ftp.denx.de/pub/u-boot
PKG_HASH:=e00e6c6f014e046101739d08d06f328811cebcf5ae101348f409cbbd55ce6900
PKG_SOURCE_SUBDIR:=$(PKG_DISTNAME)-$(PKG_VERSION)
PKG_BUILD_DIR:=$(BUILD_DIR)/$(PKG_DISTNAME)-$(PKG_VERSION)

# PKG_BUILD_DEPENDS:=fstools

include $(INCLUDE_DIR)/package.mk


define U-Boot/Default
 BUILD_TARGET:=rockchip-3568
endef

define U-Boot/linkstar-h68k-rk3568
	BUILD_SUBTARGET:=armv8
	UBOOT_CONFIG:=linkstar-h68-rk3568
	DEPENDS:=+arm-trusted-firmware-rockchip-rkbin
	NAME:=LinkstarH68k
	BUILD_DEVICES:=linkstar-h68k
	ATF_BL31:=rk3568_bl31_v1.43.elf
	ATF_BL32:=rk3568_bl32_v2.10.bin
	DDR:=rk3568_ddr_1560MHz_v1.18.bin
 export BL31=$(ATF_BL31)
 export ROCKCHIP_TPL=$(DDR)
endef

define U-Boot/test-rk3568
	BUILD_SUBTARGET:=armv8
	UBOOT_CONFIG:=test-rk3568
	NAME:=test
	BUILD_DEVICES:=test
endef



UBOOT_TARGETS := \
	linkstar-h68k-rk3568 \
	test-rk3568


define Build/Download
	$(call Build/Download/Default)
endef

define Build/Prepare
	$(call Build/Prepare/Default)
endef

define Build/Configure
endef

define Build/Compile
	$(call Build/Compile/Default,$(UBOOT_CONFIG)_defconfig)
endef


define Build/InstallDev
endef


$(eval $(call BuildPackage,uboot-rockchip-3568))
#$(eval $(call BuildPackage/U-Boot))




