# SPDX-License-Identifier: SPDX-GPL-3.0-or-later
# GPL 3.0 or later
#
# 21 Nov 2023 tahomasoft
# bacon@tahomasoft.com Erik Beck

# This Makefile is for Rockchip RK3568 boards

include $(TOPDIR)/rules.mk


# uboot version 2023.10

# Package name below commented out because download routine uses it
# As directory name to use for downloading the source from the internet
# despite use of PKG_DISTNAME below

#PKG_NAME:=uboot-rockchip-3568

ATF_BL31:=rk3568_bl31_v1.43.elf
ATF_BL32:=rk3568_bl32_v2.10.bin
DDR:=rk3568_ddr_1560MHz_v1.18.bin
PKG_DISTNAME:=u-boot
PKG_VERSION:=2023.10
PKG_RELEASE:=0


PKG_SOURCE:=$(PKG_DISTNAME)-$(PKG_VERSION).tar.bz2
PKG_SOURCE_URL:= \
	https://ftp.denx.de/pub/u-boot \
	https://mirror.cyberbits.eu/u-boot \
	ftp://ftp.denx.de/pub/u-boot
PKG_HASH:=e00e6c6f014e046101739d08d06f328811cebcf5ae101348f409cbbd55ce6900
PKG_SOURCE_SUBDIR:=$(PKG_DISTNAME)-$(PKG_VERSION)
PKG_BUILD_DIR:=$(BUILD_DIR)/$(PKG_DISTNAME)-$(PKG_VERSION)

# PKG_BUILD_DEPENDS:=fstools
PKG_BUILD_DEPENDS:=arm-trusted-firmware-rockchip-rkbin fstools

include $(INCLUDE_DIR)/u-boot.mk
include $(INCLUDE_DIR)/package.mk


define U-Boot/linkstar-h68k-rk3568
	BUILD_TARGET:=rockchip
	BUILD_SUBTARGET:=armv8
	VARIANT:=rk3568
	UBOOT_CONFIG:=linkstar-h68-rk3568
	NAME:=LinkstarH68k
	BUILD_DEVICES:=linkstar-h68k
	DEPENDS:=+PACKAGE_u-boot-linkstar-h68k-rk3568:arm-trusted-firmware-rockchip-rkbin
	PKG_BUILD_DEPENDS:=arm-trusted-firmware-rockchip-rkbin
	ATF_BL31:=rk3568_bl31_v1.43.elf
	ATF_BL32:=rk3568_bl32_v2.10.bin
	DDR:=rk3568_ddr_1560MHz_v1.18.bin
 export BL31=$(ATF_BL31)
 export ROCKCHIP_TPL=$(DDR)
endef

# stub for now

define U-Boot/bananapi-r2pro-rk3568
	BUILD_TARGET:=rockchip
	BUILD_SUBTARGET:=armv8
	VARIANT:=rk3568
	NAME:=BananaPI-r2pro
	BUILD_DEVICES:= \
		banana-pi-r2pro
	DEPENDS:=+PACKAGE_u-boot-linkstar-h68k-rk3568:arm-trusted-firmware-rockchip-rkbin
	PKG_BUILD_DEPENDS:=arm-trusted-firmware-rockchip-rkbin
# Placeholders
	ATF_BL31:=rk3568_bl31_v1.43.elf
	ATF_BL32:=rk3568_bl32_v2.10.bin
	DDR:=rk3568_ddr_1560MHz_v1.18.bin
endef


UBOOT_TARGETS := \
	linkstar-h68k-rk3568 \
	banana-pi-r2pro-rk3568

UBOOT_CONFIGURE_VARS += USE_PRIVATE_LIBGCC=yes



define Build/Configure
endef


define Build/InstallDev
endef


define Package/u-boot/install/default
endef

$(eval $(call BuildPackage/U-Boot))




